/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.LoaiHangDao;
import MODEL.LoaiHang;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyLoaiHang extends javax.swing.JFrame {
    LoaiHangDao cdLoaihang = new LoaiHangDao();
    List<LoaiHang> list = cdLoaihang.selectAll();
    /**
     * Creates new form QuanLyLoaiHang
     */
    public QuanLyLoaiHang() {
	initComponents();
	setLocationRelativeTo(null);
	fillTable(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaloaihang = new javax.swing.JTextField();
        txtTenloaihang = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaihang = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("QUAN LÝ LOẠI MẶT HÀNG");
        jLabel1.setMaximumSize(new java.awt.Dimension(125, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(125, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(125, 20));

        jLabel2.setText("Mã loại hàng:");

        jLabel3.setText("Tên loại hàng:");

        btnThem.setForeground(new java.awt.Color(0, 0, 255));
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setForeground(new java.awt.Color(0, 0, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tblLoaihang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại hàng", "Tên mặt hàng"
            }
        ));
        tblLoaihang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaihangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaihang);

        btnTimKiem.setForeground(new java.awt.Color(0, 0, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenloaihang, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                    .addComponent(txtMaloaihang)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaloaihang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenloaihang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (checkForm()) {
            them();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        sua();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblLoaihangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaihangMouseClicked
        int row = tblLoaihang.getSelectedRow();
        mouseClick(row);
    }//GEN-LAST:event_tblLoaihangMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        this.timKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(QuanLyLoaiHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(QuanLyLoaiHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(QuanLyLoaiHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(QuanLyLoaiHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new QuanLyLoaiHang().setVisible(true);
	    }
	});
    }
    LoaiHangDao loaiHangDao = new LoaiHangDao();

    public void fillTable(List<LoaiHang> list) {
        DefaultTableModel model = (DefaultTableModel) tblLoaihang.getModel();
        model.setRowCount(0);
        try {
            for (LoaiHang loaiHang : list) {
                model.addRow(new Object[]{
                    loaiHang.getMALH(), loaiHang.getTENLH()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    LoaiHang getForm() {
        LoaiHang lh = new LoaiHang();
        lh.setMALH(txtMaloaihang.getText());
        lh.setTENLH(txtTenloaihang.getText());
        return lh;

    }

    void setFrom(LoaiHang cd) {
        txtMaloaihang.setText((String) cd.getMALH());
        txtTenloaihang.setText((String) cd.getTENLH());
    }

    void them() {
        try {
            loaiHangDao.them(getForm());
            fillTable(cdLoaihang.selectAll());
            JOptionPane.showMessageDialog(this, "Thêm loại hàng thành công");
            txtMaloaihang.setText("");
            txtTenloaihang.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm loại hàng thất bại");
            e.printStackTrace();
        }
    }

    void sua() {
        try {
            loaiHangDao.SuaLH(getForm());
            fillTable(cdLoaihang.selectAll());
            JOptionPane.showMessageDialog(this, "Cập nhật loại hàng thành công");
            txtMaloaihang.setText("");
            txtTenloaihang.setText("");
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Cập nhật loại hàng thất bại");
            e.printStackTrace();
        }
    }

    void mouseClick(int row) {
        try {
            LoaiHang lh = new LoaiHang();
            String maLH = tblLoaihang.getValueAt(row, 0).toString();
            String tenLH = tblLoaihang.getValueAt(row, 1).toString();
            lh.setMALH(maLH);
            lh.setTENLH(tenLH);
            setFrom(lh);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void timKiem() {
        try {
            String tenLH = txtTenloaihang.getText();
            List<LoaiHang> lstLoaiHang = loaiHangDao.selectLH_byTen(tenLH);
            if (lstLoaiHang.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy loại hàng");
                return;
            } else {
                fillTable(lstLoaiHang);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    boolean checkForm() {
        try {
            if (txtMaloaihang.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Bạn không được để trống mã loại hàng");
                txtMaloaihang.requestFocus();
                return false;
            }
//            if (!txtMaloaihang.getText().matches("")) {
//                DialogHelper.alert(this, "Mã loại hàng không hợp lệ");
//                txtMaloaihang.requestFocus();
//                return false;
//            }
            List<LoaiHang> lstLoaiHang = loaiHangDao.selectAll();
            for (LoaiHang loaiHang : lstLoaiHang) {
                if (txtMaloaihang.getText().equalsIgnoreCase(loaiHang.getMALH())) {
                    JOptionPane.showMessageDialog(this, "Đã có mã loại hàng này. vui lòng nhập mã khác");
                    txtMaloaihang.requestFocus();
                    return false;
                }
            }

            if (txtTenloaihang.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn không được để trống ten loại hàng");
                txtTenloaihang.requestFocus();
                return false;
            }
            if (!txtTenloaihang.getText().matches("^[a-zA-Z_ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶ"
                    + "ẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợ"
                    + "ụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\s]+$")) {
                JOptionPane.showMessageDialog(this, "Ten loại hàng ko hợp lệ");
                txtTenloaihang.requestFocus();
                return false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoaihang;
    private javax.swing.JTextField txtMaloaihang;
    private javax.swing.JTextField txtTenloaihang;
    // End of variables declaration//GEN-END:variables
}
